version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    odcockpit1:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/opendlv.data
        - ~/recordings:/opt/Recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

    opendlv-logic-cfsd18-sensation-slam:
        #latest
        image: slam:test
        network_mode: "host"
        ipc: host
        volumes:
        - .:/opt/files/
        command: "opendlv-logic-cfsd18-sensation-slam --cid=${CID} --cidDan=135 --id=121 --detectConeCvId=118 --detectConeId=116 --estimationId=114
        --gatheringTimeMs=20 --sameConeThreshold=1.0 --offsetDistanceThreshold=0.7 --offsetHeadingThreshold=0.4 --refLatitude=57.719264 --refLongitude=11.957777
        --timeBetweenKeyframes=150 --coneMappingThreshold=4 --conesPerPacket=20 --lapSize=20 --stateMachineId=1401"


