version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    odcockpit1:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/opendlv.data
        - ~/recordings:/opt/Recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

    ukf:
         image: ukf:test
         network_mode: host
         ipc: host
         command: "opendlv-logic-cfsd18-sensation-ukf --cid=${CID} --cidDan=135 --id=114 --rackId=1206 --estimationId=112 --estimationIdRaw=108 --stateMachineId=1401 --wheelEncoderIdLeft=1504 --wheelEncoderIdRight=1505 --refLatitude=57.710487 --refLongitude=11.950660 --Qx=1 --Qy=1 --QvelX=0.5 --QvelY=0.2 --Qyaw=0.2 --Qheading=1 --Rx=0.2 --Ry=0.2 --RvelX=0.3 --RaccX=0.00059 --RaccY=0.01 --Ryaw=0.03 --Rheading=0.05 --m=188 --Iz=105 --g=9.82 --l=1.53 --lf=0.765 --lr=0.765 --mu=0.9"

    cfsd18-sensation-attention:
        image: attention:test
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=116 --xBoundary=4 --yBoundary=12 --groundLayerZ=-0.3 --coneHeight=0.5 --connectDistanceThreshold=0.3 --layerRangeThreshold=0.06 --minNumOfPointsForCone=10 --maxNumOfPointsForCone=300 --farConeRadiusThreshold=0.17 --nearConeRadiusThreshold=0.13 --zRangeThreshold=0.0 --inlierRangeThreshold=0.06 --dotThreshold=0.1 --inlierFoundThreshold=150 --numberOfIterations=10 --stateMachineId=1401"

