version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    odcockpit1:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/opendlv.data
        - ~/recordings:/opt/Recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

    cfsd18-sensation-attention:
        image: chalmersfsd/cfsd18-sensation-attention:pre-release-b8727c8
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=${CID} --cidCan=135 --id=117 --xBoundary=5 --yBoundary=12 --zUpperBoundary=0.6
        --groundClusterDistanceThreshold=0.3 --groundClusterSizeThreshold=60 --connectDistanceThreshold=0.15 --minNumOfPointsForCone=3
        --maxNumOfPointsForCone=300 --coneRadiusThreshold=0.15 --zRangeThreshold=0.0 --inlierRangeThreshold=0.06 --dotThreshold=0.1
        --inlierFoundThreshold=500 --numberOfIterations=30 --stateMachineId=1401 --readyStateMachine=0"


    opendlv-logic-cfsd18-sensation-slam:
        #latest
        image: chalmersfsd/opendlv-logic-cfsd18-sensation-slam:pre-release-6b141f5
        network_mode: "host"
        ipc: host
        command: "opendlv-logic-cfsd18-sensation-slam --cid=${CID} --cidDan=135 --id=121 --detectConeCvId=118 --detectConeId=117 --estimationId=115
        --gatheringTimeMs=20 --sameConeThreshold=1.0 --offsetDistanceThreshold=0.7 --offsetHeadingThreshold=0.4 --refLatitude=57.719264 --refLongitude=11.957777
        --timeBetweenKeyframes=150 --coneMappingThreshold=4 --conesPerPacket=20 --lapSize=20 --stateMachineId=1401"

    ukf:
        #latest
        image: chalmersfsd/cfsd18-perception-ukf:pre-release-40a84f4
        network_mode: host
        ipc: host
        command: "opendlv-logic-cfsd18-sensation-ukf --cid=${CID} --cidDan=135 --id=115 --slamId=121 --rackId=1206 --estimationId=112 
        --estimationIdRaw=108 --stateMachineId=1401 --wheelEncoderIdLeft=1504 --wheelEncoderIdRight=1505 --refLatitude=57.719264 
        --refLongitude=11.957777 --Qx=1 --Qy=1 --QvelX=0.5 --QvelY=0.1 --Qyaw=0.02 --Qheading=1 --Rx=0.2 --Ry=0.2 --RvelX=0.1 
        --RaccX=0.00059 --RaccY=1 --Ryaw=0.2 --Rheading=0.5 --headingInitDistance=1 --m=210 --Iz=250 --g=9.82 --l=1.53 --lf=0.765 --lr=0.765 --mu=0.9"

    cfsd18-cognition-detectconelane:
        #latest
        image: chalmersfsd/cfsd18-cognition-detectconelane:pre-release-d336e70
        network_mode: "host"
        command: "/usr/bin/cfsd18-cognition-detectconelane --cid=${CID} --verbose=0 --id=212 --detectConeId=118 --slamId=121 --simDetectConeId=231 --attentionId=116 --yawRateId=112 --speedId=114 --gpsId=114 \
        --gatheringTimeMs=50 --separationTimeMs=10 \
        --alwaysSlam=0 --guessDistance=3.2 --minGuessSeparation=1.5 --latePerpGuessing=0 --useCurveDetection=0 --maxConeAngle=1.570796325 --behindMemoryDistance=3.0 \
        --maxConeWidthSeparation=3.2 --widthSeparationMargin=1.0 \
        --maxConeLengthSeparation=5.0 --lengthSeparationMargin=1.0 \
        --nLapsToGo=3 --lapCounterLockTime=20 \
        --useOrangeLapCounter=1 --useNewConeLapCounter=1 --nMinOrangeFrames=2 --nMinDisappearanceFrames=2 \
        --useGpsLapCounter=1 --useRawGPS=0 --refLatitude=57.710482 --refLongitude=11.950813 \
        --useAccelerationMode=0 --usePathMemory=0\
        --useSkidpadMode=0"
